export const pagePaths = {
  home: "/",
  adminCatchAll: "/admin/*",
  adminDashboard: "/admin/DashboardPage",
  adminLogin: "/admin/Login",
  adminRegister: "/admin/register",
  adminTermsAndCondition: "/admin/terms-and-conditions",
  adminProfile: "/admin/profile",
  adminSettings: "/admin/settings",
  adminForgotPassword: "/admin/forgot-password",
  adminResetPassword: "/admin/reset-password",
  adminChangePassword: "/admin/change-password",
  adminBlogs: "/admin/AdminBlogsPage",
  adminReportExcel: "/admin/ProductManagement/report-excel",
  adminCreateBlogs: "/admin/AdminBlogsPage/AdminCreateBlogsPage",
  adminCreateBlogsEdit: "/admin/AdminBlogsPage/edit/:id",
  adminCreateBlogsComment: "/admin/AdminBlogsPage/comment/:id",
  addComment: "/user/blog/addComment",
  adminConcern: "/admin/ConcernsManagementPage",
  adminCreateConcern: "/admin/ConcernsManagementPage/AdminCreateConcernsPage",
  adminCreateConcernEdit: "/admin/ConcernsManagementPage/edit/:id",
  adminOrders: "/admin/orders",
  adminCreateOrders: "/admin/orders/add",
  adminCreateOrdersEdit: "/admin/orders/edit/:id",
  adminCategories: "/admin/CategoriesManagementPage",
  adminCreatePolicy: "/admin/create-policy",
  adminSubCategory:
    "/admin/CategoriesManagementPage/SubCategoriesManagementPage",
  adminSubSubCategory:
    "/admin/CategoriesManagementPage/SubSubCategoriesManagementPage",
  adminSubSubSubCategory:
    "/admin/CategoriesManagementPage/SubSubSubCategoriesManagementPage",
  adminArticalType: "/admin/ArticalTypeManagementPage",
  adminPreferenceType:
    "/admin/CategoriesManagementPage/PreferenceTypeManagementPage",
  adminStandardSize: "/admin/AdminCreateStandardArticalPage/:id",
  adminUserManagement: "/admin/UsersManagementPage",
  adminBrandManagement: "/admin/BrandsManagementPage",
  adminProductManagement: "/admin/ProductManagement",
  adminCreateBrand: "/admin/BrandsManagementPage/AdminCreateBrandsPage",
  adminCreateProducts: "/admin/ProductManagement/AdminCreateProductsPage",
  adminCreateProductSize:
    "/admin/ProductManagement/AdminCreateProductSizePage/:id",
  adminCreateProductEdit: "/admin/ProductManagement/edit/:id",
  adminCreateProductFaq: "/admin/products/faq/:id",
  adminCreateBrandEdit: "/admin/BrandsManagementPage/edit/:id",
  adminCreateCategory:
    "/admin/CategoriesManagementPage/AdminCreateCategoryPage",
  adminCreateCategoryEdit:
    "/admin/CategoriesManagementPage/CategoriesManagementPageEdit/:id",
  adminCreateSubCategory:
    "/admin/CategoriesManagementPage/AdminCreateSubCategoryPage",
  adminCreateSubCategoryEdit:
    "/admin/CategoriesManagementPage/SubCategoriesManagementPageEdit/:id",
  adminCreateSubSubCategory:
    "/admin/CategoriesManagementPage/AdminCreateSubSubCategoryPage",
  adminCreateArticalType:
    "/admin/ArticalTypeManagementPage/AdminCreateArticalPage",
  adminEditArticalType: "/admin/ArticalTypeManagementPage/edit/:id",
  adminCreatePreferenceType:
    "/admin/CategoriesManagementPage/AdminCreatePreferencePage",
  adminCreateStandardArticalType: "/admin/AdminCreateStandardArticalPage/:id",
  adminEditStandardArticalType:
    "/admin/standard-artical-type/edit/:id/:standardEdit",
  adminCreateSubSubCategoryEdit:
    "/admin/CategoriesManagementPage/SubCategoriesManagementPageEdit/edit/:id",
  adminCreatePreferenceEdit:
    "/admin/CategoriesManagementPage/AdminCreatePreferencePage/edit/:id",
  adminCreateSubSubSubCategory:
    "/admin/CategoriesManagementPage/AdminCreateSubSubSubCategoryPage",
  adminCreateSubSubSubCategoryedit:
    "/admin/CategoriesManagementPage/SubSubSubCategoriesManagementPageEdit/:id",
  adminPrivacyPolicyPage: "/admin/PrivacyPolicyPage",
  adminDisclaimerOfWarranties: "/admin/disclaimer-of-warranties",
  adminCancellationRefund: "/admin/cancellation-refund",
  adminImportProducts: "/admin/ImportProductsPage",
  adminImportProductsImages: "/admin/ImportProductsImage",
  adminImportProductsPrices: "/admin/ImportProductsPrice",
  adminHelp: "/admin/help",
  adminAbandonedCart: "/admin/AbandonedCartPage",
  adminCoupon: "/admin/CouponsManagement",
  adminCreateCoupon: "/admin/CouponsManagement/AdminCreateCouponsPage",
  adminCreateCouponEdit: "/admin/CouponsManagement/edit/:id",
  adminEmployee: "/admin/EmployeesManagementPage",
  adminCreateEmployee:
    "/admin/EmployeesManagementPage/AdminCreateEmployeesPage",
  adminCreateEmployeeEdit: "/admin/EmployeesManagementPage/edit/:id",
  adminArticleType: "/admin/ArticalTypeManagementPage",
  adminCreateArticleType:
    "/admin/ArticalTypeManagementPage/AdminCreateArticalPage",
  adminCreateArticleTypeEdit: "/admin/ArticalTypeManagementPage/edit/:id",
  adminCreateArticleTypeComment: "/admin/ArticalTypeManagementPage/comment/:id",
  adminPreferenceType: "/admin/PreferenceTypeManagementPage",
  hair: "/Hair",
  ayurveda: "/Ayurveda",
  nutrition: "/Nutrition",
  elderly: "/Elderly",
  diabetes: "/Diabetes",
  jointPain: "/JointPain",
  asthma: "/Asthma",
  wellness: "/Wellness",
  policies: "/Policies",
  userLogin: "/login",
  concerns: "/Concerns",
  brands: "/Brands",
  categories: "/Categories",
  subcategories: "/SubCategoriesManagementPage",
  subsubcategories: "/SubSubCategoriesManagementPage",
  subsubsubcategories: "/SubSubSubCategoriesManagementPage",
  listBlogs: "/Listblogs",
  aboutUs: "/Aboutus",
  blogs: "/blogs",
  blogDetails: "/blogs/:blogSlug",
  cart: "/Cart",
  contactUs: "/Contactus",
  creams: "/Creams",
  faqs: "/faq",
  offers: "/Offers",
  account: "/account",
  productDetails: "/shop/:productSlug",
  productDetails1: "/shop/:categorySlug/:productSlug",
  productDetails2: "/shop/:categorySlug/:subCategorySlug/:productSlug",
  productDetails3:
    "/shop/:categorySlug/:subCategorySlug/:subSubCategorySlug/:productSlug",
  privacyPolicy: "/Privacypolicy",
  termsAndConditions: "/terms-and-conditions",
  cancellationRefund: "/cancellation-refund",
  disclaimerOfWarranties: "/disclaimer-of-warranties",
  orderPlaced: "/order-placed/:orderId",
  products: "/products",
  topPicks: "/top-picks",
  newArrivals: "/new-arrivals",
  shopByAge: "/shop-by-age",
  productCategory: "/product-category",
  curatedProducts: "/curated-products/:offerSlug",
  myOrders: "/account?tab=my-orders",
  address: "/account?tab=address",
  myWallet: "/account?tab=my-wallet",
  myWishlist: "/account?tab=my-wishlist",
  myCoupons: "/account?tab=my-coupons",
  myAccount: "/account?tab=my-account",
  // myAccount: "/AccountTab",
  concernProduct: "/concern",
  brand: "/brand",
  brandprod: "/product-brands",
  medicalExpert: "/medical-expert",
  sellwithus: "/sellwithus",
  rateProduct: "/Rateproduct",
  adminRatingAndReview: "/admin/AdminRatingAndReviewPage",
  adminCreateRatingAndReviewEdit: "/admin/AdminRatingAndReviewPage/edit/:id",
  adminFaqManagement: "/admin/FaqManagementPage",
  adminCreateFaq: "/admin/FaqManagementPage/AdminCreateFaqsPage",
  adminCreateFaqEdit: "/admin/FaqManagementPage/edit/:id",
  adminSingleAddManagement: "/admin/SingleAddManagementPage",
  adminCreateSingleAdd:
    "/admin/SingleAddManagementPage/AdminCreateSingleAddPage",
  adminCreateSingleAddEdit: "/admin/SingleAddManagementPage/edit/:id",
  adminMultipleAddManagement: "/admin/MultipleAddManagementPage",
  adminCreateMultipleAdd:
    "/admin/MultipleAddManagementPage/AdminCreateMultipleAddPage",
  adminCreateMultipleAddEdit: "/admin/multipleAdd/edit/:id",
  adminCuratedAddManagement: "/admin/CuratedAddManagementPage",
  adminCreateCuratedAdd:
    "/admin/CuratedAddManagementPage/AdminCreateCuratedAddPage",
  adminCreateCuratedAddEdit: "/admin/curateAdd/edit/:id",
  adminSelfAddManagement: "/admin/SelfAddManagementPage",
  adminCreateSelfAdd: "/admin/selfAdd/add",
  adminCreateSelfAddEdit: "/admin/SelfAddManagementPage/edit/:id",
  addsurl: "/:slug",
  adminCreateOrder: "/admin/orders/AdminCreateOrderPage",
  adminCuratedUploadExcelSheet: "/admin/curated/upload/images/:id",
  adminPopupManagement: "/admin/PopupManagement",
  adminPopupManagementAdd: "/admin/PopupManagement/AdminCreatePopupPage",
  adminPopupManagementEdit: "/admin/PopupManagement/edit/:id",
  adminEditOrder: "/admin/orders/edit/:id",
  trackOrder: "/TrackOrder",
  adminUserWalletTransaction: "/admin/wallet-transaction",
  adminHomePageVision: "/admin/vision",
  adminHomePageMision: "/admin/mission",
  thankYou: "/thankyou",
  fasterOrder: "/faster-order",
};
