version: "3.9"

services:
  web:
    build:
      context: . # Path to your Dockerfile (root of your project)
      dockerfile: Dockerfile # Make sure it's named 'Dockerfile' (no extension)
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
